set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-open'

# Copy and paste
setw -g  mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key -n C-y run-shell '~/.tmux-paste.sh'

# popup
bind -n M-t display-popup -E "tmux new-session -A -s scratch"
bind -n M-p display-popup -E "ipython3"
bind -n M-b display-popup -E "bc -l"

# Switch panes in vim style
bind k selectp -U
bind j selectp -D
bind h selectp -L
bind l selectp -R
bind p selectw -p

set-option -g mouse on

# Reduce wait time after ESC
set -sg escape-time 0

set -g history-limit 20000

# New panes in current directory
bind '"' split-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

# New windows in current directory
bind 'c' new-window -c "#{pane_current_path}"

run -b '~/.tmux/plugins/tpm/tpm'
